language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.4
    - php: 5.5
    - php: 5.6

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - if [ $(phpenv version-name) = "7" ]; then vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml test; else phpunit --bootstrap vendor/autoload.php test; fi

after_script:
  - if [ $(phpenv version-name) = "7" ]; then composer require psr/log ; fi
  - if [ $(phpenv version-name) = "7" ]; then composer require satooshi/php-coveralls dev-master ; fi
  - if [ $(phpenv version-name) = "7" ]; then vendor/bin/coveralls -v --exclude-no-stmt ; fi
