language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - if [ $(phpenv version-name) = "7.3" ]; then vendor/bin/phpunit --whitelist src/figdice --coverage-text --coverage-clover build/logs/clover.xml test; else vendor/bin/phpunit test; fi

after_success:
  - echo "php version name = $(phpenv version-name)"
  - if [ $(phpenv version-name) = "7.3" ]; then composer require psr/log ; fi
  - if [ $(phpenv version-name) = "7.3" ]; then composer require php-coveralls/php-coveralls '^2.1' ; fi
  - if [ $(phpenv version-name) = "7.3" ]; then php vendor/bin/php-coveralls -v --exclude-no-stmt ; fi
