language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - hhvm

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - if [ $(phpenv version-name) = "7.3" ]; then vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml test; else vendor/bin/phpunit test; fi

after_script:
  - echo "php version name = $(phpenv version-name)"
  - if [ $(phpenv version-name) = "7.3" ]; then composer require psr/log ; fi
  - if [ $(phpenv version-name) = "7.3" ]; then composer require satooshi/php-coveralls dev-master ; fi
  - if [ $(phpenv version-name) = "7.3" ]; then vendor/bin/coveralls -v --exclude-no-stmt ; fi
