language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml test

after_script:
  - composer require psr/log
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt
