name: Build and Test

on:
  push:
    branches: [ "4.x" ]
  pull_request:
    branches: [ "4.x" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug
        
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: |
        mkdir -p build/logs
        vendor/bin/phpunit --whitelist src/figdice --coverage-text --coverage-clover build/logs/clover.xml test

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: build/logs/clover.xml

  coverage:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: mkdir -p build/logs

      - name: Download coverage result artifact
        uses: actions/download-artifact@v3
        working-directory: build/logs
        with:
          name: code-coverage-report

      - name: Publish coverage report
        run: |
          composer require psr/log '^2.0'
          composer require php-coveralls/php-coveralls '^2.5.3'
          php vendor/bin/php-coveralls -v --exclude-no-stmt
